#[[plugins]]
#repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffeescript'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'vim-scripts/javacomplete'
on_ft = 'java'

  [[plugins.build]]
  mac  = 'javac autoload/Reflection.java'
  unix = 'javac autoload/Reflection.java'

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = 'ruby'


[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'
